name: Build test

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install boost
      run: sudo apt update && sudo apt install libboost-all-dev
    - name: make
      run: make test
